config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  resources :items do
    resources :notes
    collection do
      get :archive_toggle
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :notes, dependent: :destroy

  validates :title, :description, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :item

  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  def index
    @items = Item.all.order(archived: :asc, due_date: :desc)
  end

  def show
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url, notice: "Item was successfully created."
    else
      redirect_to items_url, alert: "Item creation failed..."
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: "Item was successfully updated."
    else
      flash.now[:alert] = "Invalid input, item update failed..."
      render :edit, alert: "Item update failed..."
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: "Item was successfully deleted."
  end

  def archive_toggle
    @item = Item.find(params[:item_id])
    @item.update(archived: !@item.archived)
    redirect_to items_url
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :description, :due_date, :archived)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @item = Item.find(params[:item_id])
    @note = @item.notes.create(note_params)
    if @note.valid?
      redirect_to item_path(@item), notice: "Note successfully created!"
    else
      redirect_to item_path(@item), alert: "Error: Must provide body text..."
    end
  end

  def destroy
    @item = Item.find(params[:item_id])
    @note = @item.notes.find(params[:id])
    @note.destroy
    redirect_to item_path(@item), notice: "Note successfully deleted!"
  end

  private
    def note_params
      params.require(:note).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/items/_form.html.erb
<%= form_with model: item do |form| %>

  <div class="form-group mb-3">
    <%= form.text_field :title, class: "form-control mb-1", placeholder: "Title" %>
    <%= form.text_area :description, class: "form-control mb-2", placeholder: "Description", rows: "5" %>
    <div class="input-group mb-2">
      <span class="input-group-text">Due Date: </span>
      <%= form.date_field :due_date, class: "form-control", value: "#{Date.tomorrow}" %>
      <%= form.hidden_field :archived, :value => false %>
    </div>
  </div>

  <div class="form-group ms-2">
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>

<% end %>

app/views/items/edit.html.erb
<%# Render the new/edit post form in a card %>
<div class="card w-100 mx-auto mt-5 mb-3 text-dark bg-light">
  <div class="card-header">
    <p class="card-text text-center fs-4">Edit Item</p>
  </div>
  <div class="card-body">
    <%= render "form", item: @item %>
  </div>
</div>

<%# Add a back button that redirects back to the show view for the post %>
<div class="container mb-5 text-center">
  <%= link_to "Back", @item, class: 'btn btn-dark px-5' %>
</div>

app/views/items/index.html.erb
<h1 class="text-center mt-2 mb-4">L&G TODO LIST</h1>

<% if @items.empty? %>
  <%# If the items array is empty, make user aware with a card %>
  <div class="card w-75 mx-auto">
    <div class="card-header text-center">
      <p class="card-text">No Items...</p>
    </div>
  </div>
<% else %>
  <%# Otherwise, list all items as clickable links %>
  <div class="list-group mb-3">
    <%# Goes thru each item and creates a clickable list-group-item link %>
    <% @items.each do |item| %>
      <div class="position-relative">
      <%= link_to archive_toggle_items_path(item_id: item.id), class: "archive-toggle" do %>
        <span><i class="bi-<%= item.archived ? 'check-square-fill' : 'square' %>"></i></span>
      <% end %>
      <%= link_to item, class: "#{item.archived ? 'list-group-item task-done' : 'list-group-item task-undone'} d-flex justify-content-between list-group-item list-group-item-action py-3" do %>
        <span class="ms-4 <%= item.archived ? 'text-decoration-line-through' : '' %>"><%= item.title %></span>
        <span class="<%= item.archived ? 'text-decoration-line-through' : '' %>">Due: <%= item.due_date.strftime("%_m-%d-%y") %></span>
      <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<%# New item form rendered in a card %>
<div class="card w-100 mx-auto text-white bg-secondary">
  <div class="card-body">
    <%= render "form", item: Item.new %>
  </div>
</div>

app/views/items/show.html.erb
<%# Adds a back button at the bottom that takes user back to root page %>
<div class="container text-center">
  <%= link_to "<<<", root_path, class: 'btn btn-dark' %>
</div>

<%# Display the item and give the option to edit and delete it %>
<div class="card w-100 mt-3 mb-3 mx-auto text-white bg-secondary">
  <div class="card-header fs-5 fw-bold py-3 text-center">
    <%= @item.title %>
  </div>
  <div class="card-body mb-1">
    <p class="card-text"><%= simple_format(@item.description) %></p>
    <div class="text-center mb-4">
      <%= link_to "Edit", edit_item_path(@item), class: 'btn btn-primary px-4 mx-1' %>
      <%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger mx-1' %>
    </div>
    <%# Check if there are any notes for this item %>
    <% if @item.notes.empty? %>
      <%# If the notes array is empty, make user aware with a card %>
      <div class="card w-75 mx-auto mb-1 text-white bg-dark">
        <div class="card-header text-center">
          <p class="card-text">No notes...</p>
        </div>
      </div>
    <% else %>
      <%# Renders each note one by one using the partial expansion feature %>
      <%= render @item.notes %>
    <% end %>

    <%# New note form rendered in a card %>
    <div class="card w-75 mx-auto mb-2 text-white bg-dark">
      <div class="card-body">
        <%= render "notes/form" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<%# Styles alert with bootstrap and make it red to signify an error %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_notices.html.erb
<%# Styles notice with bootstrap and make it green to signify success %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">

    <title>L&G TODO LIST</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background:#739c7c;">
    <!-- Put body in a bootstrap container -->
    <div class="container pt-3 pb-3">
      <!-- If any notices or alerts are sent, render them with corresponding partial -->
      <% if notice %>
        <%= render 'layouts/notices' %>
      <% end %>
      <% if alert %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Bootstrap script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: [@item, @item.notes.build] do |form| %>

  <div class="form-group h-100 mb-3">
    <%= form.text_area :body, class: "form-control", placeholder: "Body", rows: "5" %>
  </div>
  <div class="form-group text-center">
    <%= form.submit "Submit", class: "btn btn-sm btn-warning" %>
  </div>

<% end %>

app/views/notes/_note.html.erb
<div class="card w-75 mx-auto mb-1 text-white bg-dark">
  <div class="card-body">
    <p class="card-text"><%= simple_format(note.body) %></p>
    <div class="text-center">
      <%= link_to 'Delete', [note.item, note], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
    </div>
  </div>
</div>